In [16]:
# one hot encoding using onehotencoder.

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [17]:
# Building a dummy employee dataset.

data = {
    "employee_id": [10, 20, 15, 25, 30],
    "gender": ['M', 'F', 'F', 'M', 'F'],
    "remarks": ['good', 'nice', 'good', 'great','nice']
}

print("data before going to datafreame: ",data)

# convert into a pandas dataframe.
df = pd.DataFrame(data)

df

data before going to datafreame:  {'employee_id': [10, 20, 15, 25, 30], 'gender': ['M', 'F', 'F', 'M', 'F'], 'remarks': ['good', 'nice', 'good', 'great', 'nice']}

   employee_id gender remarks
0           10      M    good
1           20      F    nice
2           15      F    good
3           25      M   great
4           30      F    nice

In [18]:
df.dtypes

employee_id     int64
gender         object
remarks        object
dtype: object

In [19]:
# we only need catagorical columns so 'object' dtype columns.
catagorical_cols = df.select_dtypes(include=['object']).columns.tolist()

In [20]:
# Initialize OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)  # need output in numpy array formate
# not sparse matrix formate.

In [21]:
# now it's to apply one hot encoding on catagorical columns.

one_hot_encoded = encoder.fit_transform(df[catagorical_cols])

In [22]:
# create a dataframe with one hot encoded column.
# we use get_feature_names_out to get the column names for one hot encoded columns.

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(catagorical_cols))
one_hot_df

   gender_F  gender_M  remarks_good  remarks_great  remarks_nice
0       0.0       1.0           1.0            0.0           0.0
1       1.0       0.0           0.0            0.0           1.0
2       1.0       0.0           1.0            0.0           0.0
3       0.0       1.0           0.0            1.0           0.0
4       1.0       0.0           0.0            0.0           1.0

In [24]:
# now I need to add both the dataframes 'df' and 'one_hot_df' together.

df_encoded = pd.concat([df, one_hot_df], axis=1) # I want column wise.
df_encoded

,employee_id,gender,remarks,gender_F,gender_M,remarks_good,remarks_great,remarks_nice
0,10,M,good,0.0,1.0,1.0,0.0,0.0
1,20,F,nice,1.0,0.0,0.0,0.0,1.0
2,15,F,good,1.0,0.0,1.0,0.0,0.0
3,25,M,great,0.0,1.0,0.0,1.0,0.0
4,30,F,nice,1.0,0.0,0.0,0.0,1.0

In [25]:
# now drop the original catagorical columns.
df_encoded.drop(catagorical_cols, axis=1, inplace=True) # inplace=True means I want to change the original dataframe.
df_encoded

   employee_id  gender_F  gender_M  remarks_good  remarks_great  remarks_nice
0           10       0.0       1.0           1.0            0.0           0.0
1           20       1.0       0.0           0.0            0.0           1.0
2           15       1.0       0.0           1.0            0.0           0.0
3           25       0.0       1.0           0.0            1.0           0.0
4           30       1.0       0.0           0.0            0.0           1.0